# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: v:/ZEDBOARD/vivado/zynq_soc/ZEDBOARD.srcs/sources_1/bd/zynq_soc/ip/zynq_soc_auto_cc_2/zynq_soc_auto_cc_2.xci
# IP: The module: 'zynq_soc_auto_cc_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: v:/ZEDBOARD/vivado/zynq_soc/ZEDBOARD.srcs/sources_1/bd/zynq_soc/ip/zynq_soc_auto_cc_2/zynq_soc_auto_cc_2_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_soc_auto_cc_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: v:/ZEDBOARD/vivado/zynq_soc/ZEDBOARD.srcs/sources_1/bd/zynq_soc/ip/zynq_soc_auto_cc_2/zynq_soc_auto_cc_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_soc_auto_cc_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: v:/ZEDBOARD/vivado/zynq_soc/ZEDBOARD.srcs/sources_1/bd/zynq_soc/ip/zynq_soc_auto_cc_2/zynq_soc_auto_cc_2.xci
# IP: The module: 'zynq_soc_auto_cc_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: v:/ZEDBOARD/vivado/zynq_soc/ZEDBOARD.srcs/sources_1/bd/zynq_soc/ip/zynq_soc_auto_cc_2/zynq_soc_auto_cc_2_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_soc_auto_cc_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: v:/ZEDBOARD/vivado/zynq_soc/ZEDBOARD.srcs/sources_1/bd/zynq_soc/ip/zynq_soc_auto_cc_2/zynq_soc_auto_cc_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_soc_auto_cc_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
