# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: v:/SOBELDETECT/DEBUG/RELEASED/ZEDBOARD/vivado/zynq_soc/ZEDBOARD.srcs/sources_1/bd/zynq_soc/ip/zynq_soc_auto_cc_5/zynq_soc_auto_cc_5.xci
# IP: The module: 'zynq_soc_auto_cc_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: v:/SOBELDETECT/DEBUG/RELEASED/ZEDBOARD/vivado/zynq_soc/ZEDBOARD.srcs/sources_1/bd/zynq_soc/ip/zynq_soc_auto_cc_5/zynq_soc_auto_cc_5_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_soc_auto_cc_5'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: v:/SOBELDETECT/DEBUG/RELEASED/ZEDBOARD/vivado/zynq_soc/ZEDBOARD.srcs/sources_1/bd/zynq_soc/ip/zynq_soc_auto_cc_5/zynq_soc_auto_cc_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_soc_auto_cc_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: v:/SOBELDETECT/DEBUG/RELEASED/ZEDBOARD/vivado/zynq_soc/ZEDBOARD.srcs/sources_1/bd/zynq_soc/ip/zynq_soc_auto_cc_5/zynq_soc_auto_cc_5.xci
# IP: The module: 'zynq_soc_auto_cc_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: v:/SOBELDETECT/DEBUG/RELEASED/ZEDBOARD/vivado/zynq_soc/ZEDBOARD.srcs/sources_1/bd/zynq_soc/ip/zynq_soc_auto_cc_5/zynq_soc_auto_cc_5_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_soc_auto_cc_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: v:/SOBELDETECT/DEBUG/RELEASED/ZEDBOARD/vivado/zynq_soc/ZEDBOARD.srcs/sources_1/bd/zynq_soc/ip/zynq_soc_auto_cc_5/zynq_soc_auto_cc_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_soc_auto_cc_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
